name: FrontierHealth.co
favicon: null
layout_spectrum: 0.5660007451660931
typography_spectrum: 0.8987573180347681
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#75cf3b'
    - '#134289'
    - '#a7c3cb'
    - '#b9e699'
  brandStrength: 0.4861526044551283
  lightness: 0.44196011032909155
  saturation: 0.5926101442892104
  rhythmicContrast: 0.8003893154673278
purpose: []
